{% set name = "checkstyle" %}
{% set version = "10.18.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/checkstyle/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: 6cb222005132214d19afeb4e5dddf56a4fc8d0197794904669c35455d2a14c9d
  folder: checkstyle

build:
  noarch: generic
  number: 0

requirements:
  build:
    - maven
    - openjdk
  run:
    - openjdk

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/checkstyle/{{ name }}
  license: LGPL-2.1-or-later AND Apache-2.0
  license_file:
    - checkstyle/LICENSE
    - checkstyle/LICENSE.apache20
    - checkstyle/target/generated-resources/licenses/
  summary: Checkstyle is a development tool to help programmers write Java code that adheres to a coding standard
  dev_url: https://github.com/checkstyle/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
