context:
  version: "13.3.0"

package:
  name: checkstyle
  version: ${{ version }}

source:
  url: https://github.com/checkstyle/checkstyle/archive/checkstyle-${{ version }}.tar.gz
  sha256: 172530fca9f5bf342a89f794c84e3fc77bff3e2494a267500f677483fee03ec0
  target_directory: checkstyle

build:
  number: 0
  noarch: generic

requirements:
  build:
    - maven
    - openjdk
  run:
    - openjdk

tests:
  - script:
      - checkstyle --help

about:
  license: LGPL-2.1-or-later AND Apache-2.0
  license_file:
    - checkstyle/LICENSE
    - checkstyle/LICENSE.apache20
    - checkstyle/target/generated-resources/licenses/
  summary: Checkstyle is a development tool to help programmers write Java code that adheres to a coding standard
  homepage: https://github.com/checkstyle/checkstyle
  repository: https://github.com/checkstyle/checkstyle

extra:
  recipe-maintainers:
    - danielnachun
