context:
  version: "12.1.0"

package:
  name: checkstyle
  version: ${{ version }}

source:
  url: https://github.com/checkstyle/checkstyle/archive/checkstyle-${{ version }}.tar.gz
  sha256: 44a48b9807af60a827a3ecaeba064b4893c9e55aae7cb9417320a9b7978a28a4
  target_directory: checkstyle

build:
  number: 0
  noarch: generic

requirements:
  build:
    - maven
    - openjdk
  run:
    - openjdk

tests:
  - script:
      - checkstyle --help

about:
  license: LGPL-2.1-or-later AND Apache-2.0
  license_file:
    - checkstyle/LICENSE
    - checkstyle/LICENSE.apache20
    - checkstyle/target/generated-resources/licenses/
  summary: Checkstyle is a development tool to help programmers write Java code that adheres to a coding standard
  homepage: https://github.com/checkstyle/checkstyle
  repository: https://github.com/checkstyle/checkstyle

extra:
  recipe-maintainers:
    - danielnachun
